#!/bin/sh

MYPATH="`dirname \"$0\"`"
MYPATH="`( cd \"$MYPATH\" && pwd )`"

cc -o $MYPATH/src/c/detect_hooks/detect_hooks $MYPATH/src/c/detect_hooks/detect_hooks.c -lkvm

kldload $MYPATH/src/c/detect_ports/detect_ports.ko

$MYPATH/src/c/detect_hooks/detect_hooks sys_read

if [ $? -eq 1 ]
then return 1
fi

return 0
